name: env variables

on:
  push:
    branches:
      main

env:
  LOCAL_VAR: 'local var'

jobs:
  one:
    runs-on: ubuntu-latest
    
    environment: development

    steps:
    - name:  Read a variable
      run: echo ${{ vars.GLOBAL_VAR }}

    - name:  GitHub staff
      run: echo ${{ github.repository }}        

    - name:  Read a local variable
      run: echo ${{ env.LOCAL_VAR }}

    - name:  Read a env variable
      run: echo ${{ env.ENV_VAR }}
